configuration:
  # Настройки хранилища изображений
  storage:
    minio:
      enabled: true
      address: "http://localhost:9090"
      accessKey: "W8Jvj22cKJ6wTuTM"
      secretKey: "JDKKgnNNWywVjupNFOkUOfDsMlR6ep0D"
    local:
      enabled: false
      path: "media"

  # Настройка директорий и формата для итоговых изображений
  formats:
    avatars:
      type: "png"
      width: 128
      height: 128
    covers:
      type: "jpg"
      width: 310
      height: 500