logging:
  file:
    path: logs

spring:
  banner:
    location: banner.txt
    charset: utf-8

minio:
  address: "http://localhost:9090"
  accessKey: "W8Jvj22cKJ6wTuTM"
  secretKey: "JDKKgnNNWywVjupNFOkUOfDsMlR6ep0D"

upload:
  types:
    avatars:
      format: "png"
      width: 128
      height: 128
    covers:
      format: "jpg"
      width: 310
      height: 500