logging:
  file:
    path: logs

spring:
  banner:
    location: banner.txt
    charset: utf-8

#----------------------------------------------------------------
configuration:
  # Настройки хранилища изображений
  storage:
#    minio:
#      address: "http://localhost:9090"
#      accessKey: "W8Jvj22cKJ6wTuTM"
#      secretKey: "JDKKgnNNWywVjupNFOkUOfDsMlR6ep0D"
    local:
      path: "media"

  # Настройка директорий и формата для итоговых изображений
  formats:
    avatars:
      type: "png"
      width: 128
      height: 128
    covers:
      type: "jpg"
      width: 310
      height: 500